### ISSUE TITLE
People are forgetting their holdings 

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1035]
Every week there is a handful of people who forget to add holdings to their newly created records for prints. Can we make it easier to add holdings at the point of cataloging?

When creating a new record for EDT, I wonder if there could be a direct link from the "actions" to adding holdings, such as changing the "Save and close" button to "Save and add holdings". Or activating the link "Save and close" only after holdings are attached. It would be nice if there was a way to catch people right when they are cataloging (instead of discovering the error days later, after they have moved on).

**Comment by xhero** [comment]
I could probably try to activate the validation for this, so the user gets a warning, or maybe a dialog box. The user needs to have the record before adding the holding, so I cannot block that.

**Comment by jenniferward** [comment]
Or, the "holdings" element appears at the bottom of the Print template so that the cataloger does both (bib record plus holdings) at once?

**Comment by xhero** [comment]
I see to options here:
* Show a big error message, but non blocking - we do not want to end up in the case that cataloguers cannot save their changes because the validation prevents it, and to add a holding one must exit the source edit view
* Try to see if it is possible to jump directly to the "new holding" page the first time the source is saved to "force" the addition of a holding, and show a message as above is the operation is cancelled.

The first option is relatively easy, for the second one I can see it it can be done

**Comment by jenniferward** [comment]
Actually we would need this for LED (printed libretti) and TED (printed treatises) as well.

**Comment by xhero** [comment]
Done in 7.1.2
