### ISSUE TITLE
Records shouldn't link to themselves

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1138]
It could be a service to users to have an error message appear when they try to link the field 773, 774, or 787 to the current record. It's probably a copy and paste error, but it is apparently not at all obvious to users when it is happening (because they keep trying to do it a half dozen times). Perhaps "Record cannot link to itself", then block the ability from those fields equaling the 001.

**Comment by xhero** [comment]
From 7.1.2 collections cannot link anymore to collections, so this will be mitigated. 787 on the other hand can still connect to collections, so I added a backend validation that will block saving.
A frontend validation is not possible (yet) as two validations on the same tag (787 w) are necessary and due to limitations in the validation stack it is not possible to implement them at this time. In a future release we could have a project to fix this if needed. In the meantime, the backend validation completely prevents this error.
