### ISSUE TITLE
Material groups in Collections

### ISSUE THREAD

**Issue by xhero** [rism-digital/muscat#1142]
Related to #1122.
Should collections contain material groups that cam be redundant with the content or mixed (print, ms, etc)?

**Comment by jenniferward** [comment]
I'd add composite volumes to the discussion because it is a similar issue: Each linked record already has a 593, so the question is what kind of 593 a composite volume needs. Options:
- No 593 (my personal preference, since essentially a composite volume record describes a "container" and not a page with notes on it)
- One 593 for each type (messy)
- "Other" (of no added value to the user, in my opinion)

**Comment by xhero** [comment]
I think this is quite outdated as 593 after we implemented it?

**Comment by jenniferward** [comment]
Yes, we are taking care of this elsewhere.
