### ISSUE TITLE
Institutions, filters, is in folder

### ISSUE THREAD

**Issue by Docudoctor** [rism-digital/muscat#1189]
Please make the institution records of a folder listed in "Is in folder" available by the action "Filter". 
Thanks,
Guido

**Comment by jenniferward** [comment]
@Docudoctor Is this what you mean?
https://muscat.rism.info/admin/institutions?utf8=%E2%9C%93&q%5Bid_with_integer%5D=folder_id%3A747&commit=Filter&order=id_desc

![image](https://user-images.githubusercontent.com/18663291/149980882-52eeea92-c6f7-47a5-9863-97b98e11dbf4.png)



@xhero Nothing happens when I click "filter" ("no institutions found"). Is that a bug?

**Comment by Docudoctor** [comment]
Yes.

**Comment by xhero** [comment]
Fixed
