### ISSUE TITLE
"Delete" button confirmation for folders

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1241]
The "Delete" buttons for folders [on the general Folders page](https://muscat.rism.info/admin/folders) and on a [specific folder page](https://muscat.rism.info/admin/folders/843) show different messages to confirm before deleting. Can we make them the same?

(1) On the general Folders page, you click Delete and you get this message:
![image](https://user-images.githubusercontent.com/18663291/165545148-c976faac-6ba8-4832-becb-cb635819d229.png)

(2) On a specific folder page, you click Delete and you get this message:
![image](https://user-images.githubusercontent.com/18663291/165545327-a59ff868-6927-4f23-b236-ee6a0efcca5c.png)

I prefer (1) but I would rather change the message to make it more folder-specific:
Are you sure you want to delete this folder?

**Comment by xhero** [comment]
I made the messages all like (1), which also affected deleting Sources (it would ask to delete this "version"). Unfortunately it is not really possible to add "folder" (or "source"...) to the message since it is hardcoded in the framework and I could only show it on some messages (the ones in the show page with the red button but not in the listing).

**Comment by jenniferward** [comment]
That should be fine -- it's only ZR who can delete sources and we can deal with that message.
