### ISSUE TITLE
593 subtags with composite template

### ISSUE THREAD

**Issue by HirschSt** [rism-digital/muscat#1270]
the table in #1248 doesn't contain values for $a and $b. Suggestion is to take 'other' for both fields

**Comment by jenniferward** [comment]
Our guidelines say:

> Optionally, only fill this out if the entire volume is of the same source type. In many cases, this will be left
> blank. Do not select "Other." 

but this was just an accommodation for the current 593 structure. I'd be happy to for it to go in a different direction. I'm also leaning towards `$aComposite$bComposite`, but was unsure if there are implications for other platforms.

**Comment by ahankinson** [comment]
Would that mean we could have: 

 - Record type: Composite volume
 - Source type: Composite
 - Content type: Composite

for a record? Is this an overuse of the word composite?

Maybe instead of "Composite" for content type we can have "Mixed"? It seems that a Composite is used to describe non-homogenous items, so having some value for the "Content" that describes the fact that it contains heterogenous material would be more descriptive than just re-using "Composite"?

So `$aComposite$bMixed`?

**Comment by jenniferward** [comment]
That's true, but's not always mixed, though: you might have a composite volume made up of only prints. https://muscat.rism.info/admin/sources/1001214473

**Comment by ahankinson** [comment]
But $b isn't the source type, is it?  it's "Notated music" or "Libretto" or "Treatise". In that case you can describe a composite volume that is all prints, but both notated music and treatise ("Mixed").

**Comment by lpugin** [comment]
I agree that "Mixed" would be much better.

**Comment by jenniferward** [comment]
Do I understand your suggestion correctly? For composites:
$a: 
Composite

$b:
Notated music
Libretto
Treatise
Mixed

**Comment by HirschSt** [comment]
So for the maintenance with composites we have 
- 593$a Composite
- 593$b Mixed
