### ISSUE TITLE
Changes to 110$g in Institutions (Library siglum)

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/muscat#1279]
It doesn't look like changes to the field 110$g in Institutions (Library siglum) are registering in the "Show modifications".
https://muscat.rism.info/admin/institutions/30006007/edit
Guido and I went back and forth changing the siglum as an experiment (we changed it back, so you can't really reconstruct it now) but it never showed up:
![image](https://user-images.githubusercontent.com/18663291/185363606-3171c66c-2b0d-4e52-8b5b-acc8dd3cbcb5.png)
The Diff shows a blank area.
More concretely, this siglum actually was changed by RISM Greece (from GR-Npl to GR-NApl) but it does not show up on any of the diffs.

I don't think it's showing up on the "Compare versions" either? (The field Associated country was in fact not changed.)
![image](https://user-images.githubusercontent.com/18663291/185364322-0ef0ecac-1317-46c9-9c01-5c76b93dad81.png)

Is there a way to make sure all the fields show up in the diff?

**Comment by HirschSt** [comment]
https://github.com/rism-digital/muscat/blob/ef7aa7441e22de6b469970862d79764b58843bc8/app/admin/compare_versions.rb#L18

Maybe this is the reason...

**Comment by xhero** [comment]
The original siglum change is captured in this snapshot: Thursday 16 July 2020 - 17:13
The problem I think is the "grace period", not all saves are saved as an old version: after the first time the record is saved one "old version" for the diff is made, but then for 43200 seconds (12 hours) no more "old versions" for the record are created (for the current user, other users will make a version if saving). This means that if you do many changes in a short time you will not see them as they are not saved at all. The reason is that we have 3.2 million versions and we need to keep a balance between versions created / how many times a record is saved in a row.
One solution could be to force an "old version" to be created when a couple critical tags are touched, like 110$g, so we always know it was modified.

**Comment by jenniferward** [comment]
For some reason we didn't see it back in August, but I see it now on the "Diff" for Thursday 16 July 2020 - 17:13:

![image](https://user-images.githubusercontent.com/18663291/225672443-ea841aa9-8cd5-4098-b122-5bf0bf698313.png)

**Comment by jenniferward** [comment]
Seems to be working as it ought to.
