### ISSUE TITLE
Authority institutions, naming of MARC field (670 $b) in German

### ISSUE THREAD

**Issue by Docudoctor** [rism-digital/muscat#1327]
Please change in the German version of Muscat the naming of MARC field (670 $b) into "Fundstelle". 
All other language versions are correct.
Thanks, Guido

**Comment by alexandermarxen** [comment]
Apparently, the name of the field was also changed to authority persons as part of this change. However, the usage in this standards database is different. Please change here again to "Ansetzung laut Literaturnachweis". If this is not possible (because the field name must be identical), please use another subfield.
