### ISSUE TITLE
Move Sigla to 094

### ISSUE THREAD

**Issue by ahankinson** [rism-digital/muscat#1590]
This is a proposal to move the sigla field in institutions from `110 $g` to `024`. This move will allow for the capture of obsolete sigla, as well as 024 being a more appropriate field for this kind of data. (`024` is "Other Standard Identifier", whereas `110 $g` is "Miscellaneous Information")

The new arrangement would be: 

- `$a`: Non-Repeatable. Holds the current siglum for an institution
- `$2`: Non-Repeatable. Would be the source of identifier, likely the string `rism`
- `$q`: Non-Repeatable. Would be the string `siglum` to mark the RISM identifier as a RISM siglum
- `$z`: Repeatable. Would hold all previous sigla that were assigned to that institution. 

So, the 024 for https://rism.online/institutions/30077306 would be: 

```
=024  ## $aV-CVbav $2rism $qsiglum $zI-RVat
```

One feature that was requested in the discussions of this change was that the Siglum entry be visually kept with the header information in `110` and not held in the "General" 024 section. This is to keep all the institution's "vitals" in one place.

So a user-friendly implementation might have a dedicated 024 entry in institutions in the same block as the `110`, with `$2` and `$q` already filled in when the record is saved, and the cataloger only needs to supply the values for `$a` and `$z`. 

The data would need to be migrated. Since we don't have any formal way of tracking former sigla, there is no data to be migrated for `$z`, and these values would need to be supplied _post hoc_. 

We would also need to inform the BSB of the potential change in data, and modify RISM Online once the data migration has happened.

**Comment by lpugin** [comment]
Since it seems difficult to find a dedicated place for the RISM sigla in MARC and that having it in 024 in Muscat would need tailored developments, maybe we can consider the following option:

1. We use an internal `094` modelled after 024 that is a non-repeatable and with the subfield as suggested by @ahankinson above. That is, a non-repeatable`$a` for the current siglum, and a repeatable `$z` for olim sigla.
2. In Muscat, `094` is labelled "RISM siglum information" and place closed to `110`. `110` `$g` is removed in Muscat.
3. In the export to MarcXML (SRU, BSB, VIAF), `094` is converted to `024` with an additional `$2` (one problem is that `rism` is not an official code, though. This needs to be clarified.). `110` `$g` would be added in the export.

The compromise would be:
* No custom development for handling siglum instances of 024 in Muscat
* A dedicated place for curating sigla in Muscat
* Proper MARC use (024) and siglum in 110 for backward compatibility and clarity

**Comment by lpugin** [comment]
Looking at the possible places for the sigla, I previously thought about [035](https://www.loc.gov/marc/authority/ad035.html). @ahankinson pointed out that this would not be acceptable because 035 is meant to be a number. However, looking at some usage of it, I can see that, for example, LC and GND use it with values that are not strictly speaking a number. See [this](https://id.loc.gov/authorities/names/n79021425.marcxml.xml) example. So if we are looking at an alternative to the proposal I made above, then `035` looks like an acceptable option to me.

**Comment by ahankinson** [comment]
`035` doesn't seem to have a `$q` for an application note, or a `$2` for the source / assigning authority. The convention seems to be to put that in the front of the number, e.g., `(CaBVaU)2835210335`, which I don't think we want to do?

**Comment by lpugin** [comment]
Yes, you are right. I guess it would be something like `(rism)V-CVbav`, or `(DE-633)V-CVbav`

**Comment by lpugin** [comment]
What I am saying is that the export can add the `(DE-633)`. In the internal MARC data and in the editor we would have only `V-CVbav`. Only the exported MARC would show `(DE-633)V-CVbav`. That something we do in other places (e.g., `$0` being `123` in the internal MARC, and `sources/123` in the exported MARC.

**Comment by xhero** [comment]
Standby: waiting for report from RISM C people

**Comment by jenniferward** [comment]
Reply from Series C group: Taking as an example https://muscat.rism.info/admin/institutions/30006007?view=MARC21
```
=024 8#$aGR-NApl$zGR-Npl
=110 1#$aPeleponnēsiako Laographiko Hidryma$cNáfplion
```

**Comment by xhero** [comment]
This is how the propose it should be?

**Comment by jenniferward** [comment]
Yes, that is their proposal: Delete 110$g and store current sigla and old sigla in 024.

**Comment by ahankinson** [comment]
Summary of decision:

 - `094 $a (NR)` will hold the current siglum for the institution
 - `094 $2 (NR)` will hold the string `rism`
 - `094 $q (NR)` will hold the string `siglum`
 - `094 $z (R)` will hold the former sigla
 - Migrate all existing data from `110 $g` to `094 $a`
 - On export, the `094` will be converted to an `024` with the same subfields
 - On export, `094 $a` will also be exposed as `110 $g` for the near future. It may disappear at some point, but this is unclear. 
 - There are concerns from @Docudoctor about the positioning of such inputs in the edit view, so we need to take care to position the fields close to the existing `110` input fields.

**Comment by xhero** [comment]
For all your testing pleasure, it is online on -test

**Comment by ahankinson** [comment]
I think this is now fixed 🎉
