### ISSUE TITLE
Add new language in 041

### ISSUE THREAD

**Issue by MFalletta** [rism-digital/muscat#1679]
Please add to the 041$a, $h drop-down menus:

roa = ~~Italian, Old (to 1300)~~ Romance (Other)

**Comment by ahankinson** [comment]
`roa` is "Romance (Other)" in the MARC code list, so that could include French or Spanish... 

https://www.loc.gov/marc/languages/language_code.html

**Comment by MFalletta** [comment]
I found it here: https://www.loc.gov/marc/languages/language_name.html#i under **Italian, Old (to 1300)**

Can we differentiate further?

**Comment by ahankinson** [comment]
The problem is that all of these languages are also covered under the `roa` code:

```
Anglo-Norman
Cajun French
Franco-Provençal
Franco-Venetian
Italian, Old (to 1300)
Ladin
Portuñol
Spanish, Old (to 1500)
```

 If `roa` is stored for multiple languages in the database, we can't then tell what the original language was when it was added. 

Can the label be "Romance (Other)" and an instruction given to use that for Old Italian?

**Comment by MFalletta** [comment]
Yes, we can use 546 $a to make an annotation.

**Comment by ahankinson** [comment]
I've modified the original ticket to clarify -- please let me know if that looks OK!

**Comment by MFalletta** [comment]
That's fine!
