### ISSUE TITLE
Validate PAE with Verovio

### ISSUE THREAD

**Issue by MFalletta** [rism-digital/muscat#901]
Es stosse immer wieder auf Incipits mit Leerzeichen am Anfang oder auch mittendrin. Lassen sich die Blanks auf den Takt- (@ ), Vorzeichen- ($)  und Schlüsselwechsel (%) eingrenzen?

**Comment by xhero** [comment]
Yes: I can make a validation that raises a warning if any of these fields contain a space. Only at the beginning?

**Comment by jenniferward** [comment]
Another $p problem: people sometimes enter " [a quotation mark] instead of '' [two apostrophes]. The quotation mark should raise a warning.

**Comment by fjorba** [comment]
> Another $p problem: people sometimes enter " [a quotation mark] instead of '' [two apostrophes]. The quotation mark should raise a warning.

FYI, I've just seen the same problem in #885.

**Comment by jenniferward** [comment]
@fjorba Yes, thanks, that is known. The problem in 885  is more of a RISM Central Office problem than a Muscat problem.

**Comment by jenniferward** [comment]
Here is a single list of useful validations for 031 - all with the aim of preventing errors and reducing the need for later corrections.

$a, b, c: These should always be filled out. Blank fields here should not be allowed. $a should almost always be a 1 (there are rare exceptions). It would be good if a warning could appear if $a is a value other than 1. There shouldn't be two instances of identical $a, b, c in one record (i.e., not 1.1.1 and 1.1.1).

$n: Only capital letters A-G should be allowed, except for initial x or b
$n: Field should begin with x, b, or capital letter A-G
$n: Illogical key signatures should be flagged with a warning. Some may in fact be correct as on the source, but typos are always a possibility (like FCC instead of FCG). The following are valid:
xF
xFC
xFCG
xFCGD
xFCGDA
xFCGDAE
xFCGDAEB
bB
bBE
bBEA
bBEAD
bBEADG
bBEADGC
bBEADGCF


$o C should not be allowed. Perhaps in general, letters other than c or o should not be allowed (though there might be exceptions).


$p Incipits should begin with a certain inventory of signs; beginning with %, @ , or $ should be unlikely. 
$p Incipits should contain only a certain inventory of signs. See #993.  
$p Spaces at the beginning of the field should not be allowed
$p  " [a quotation mark] instead of '' [two apostrophes] should not be allowed. Other characters that are sometimes confused: # instead of x, X instead of x, N instead of n
$p Spaces in the middle of the field should not be allowed, with the exception of a space following a change of clef with %, key with $, or time signature with @ .
Examples: 
%C-1 '2A
%C-1 $xFC '8B
@3/2 '1C
$nBE $xFC
$p In the same way, occurrences of % or @ or $ without a space within a certain number of characters should be flagged.

$s is for imported data and should trigger a warning if it is filled in.

**Comment by xhero** [comment]
I'm consolidating all 031 validation tickets in this one, PAE error highlighting will be implemented in 8.0

**Comment by lpugin** [comment]
These are the current list of messages.
```cpp
    { ERR_001_EMPTY, "Input is empty" },
    { ERR_002_JSON_PARSE, "Cannot parse the JSON input" },
    { ERR_003_JSON_KEY, "No 'data' key in the JSON input" },
    { ERR_004_KEY_SPACE, "Missing space character after a key signature change" },
    { ERR_005_CLEF_SPACE, "Missing space character after a clef change" },
    { ERR_006_TIMESIG_SPACE, "Missing space character after a meter signature change" },
    { ERR_007_REP_EMPTY, "Empty repeated figure" },
    { ERR_008_REP_MARKER, "New repetition marker 'f' occurs within an open repetition group" },
    { ERR_009_REP_OPEN, "Unclosed repetition figure at the end of a measure" },
    { ERR_010_REP_UNUSED, "Repeated figure never repeated" },
    { ERR_011_REP_NO_FIGURE, "Repetition marker 'f' not after a figure end" },
    { ERR_012_REP_NOT_BEGIN, "Repetition marker 'i' is not at the beginning of a measure" },
    { ERR_013_REP_NO_CONTENT, "Repetition marker 'i' encountered with no content to repeat" },
    { ERR_014_REP_NO_BARLINE, "Repetition marker 'i' is not followed by a barline" },
    { ERR_015_MREST_INVALID, "Invalid (multi) measure rest '=' after a '='" },
    { ERR_016_MREST_NUMBER, "Invalid (multi) measure rest number starting with 0" },
    { ERR_017_TRILL_INVALID, "Invalid 't' not after a note" },
    { ERR_018_FERMATA_NESTED, "Invalid nested fermata character '(' after a '('" },
    { ERR_019_ACCID_NO_NOTE, "Missing note after an accidental" },
    { ERR_020_CHORD_NOTE_BEFORE, "A chord marker '^' should be preceded by a note" },
    { ERR_021_CHORD_NOTE_AFTER, "A chord marker '^' should be followed by a note" },
    { ERR_022_BEAM_MENSURAL, "Beams are not supported with mensural notation" },
    { ERR_023_BEAM_NESTED, "Nested beams are not supported" },
    { ERR_024_BEAM_CLOSING, "Extraneous closing beam character" },
    { ERR_025_BEAM_OPEN, "Beam is not closed at the end of a measure" },
    { ERR_026_GRACE_NESTED, "Nested grace groups are not supported" },
    { ERR_027_GRACE_CLOSING, "Extraneous closing grace group" },
    { ERR_028_GRACE_OPEN, "Grace group is not closed at the end of a measure" },
    { ERR_029_GRACE_UNRESOLVED, "Invalid 'q' after an unresolved 'q'" },
    { ERR_030_GRACE_DURATION, "Duration should not be specified for acciaccatura 'g'" },
    { ERR_031_GRACE_NO_NOTE, "Grace note 'q' or 'g' is not followed by a note" },
    { ERR_032_TUPLET_NESTED, "Nested tuplets are not supported" },
    { ERR_033_TUPLET_CLOSING, "Extraneous closing tuplet ')'" },
    { ERR_034_TUPLET_NUM, "Extraneous tuplet numerator marker ';'" },
    { ERR_035_TUPLET_OPEN, "Tuplet is not closed at the end of a measure" },
    { ERR_036_TUPLET_NUM_NUMBER, "Invalid number within tuplet numerator" },
    { ERR_037_TIE_PITCH, "Invalid tie between two notes with mismatched octave and/or pitch" },
    { ERR_038_TIE_OPEN, "Invalid tie '+' sign occuring when previous tie has not been closed" },
    { ERR_039_TIE_NO_NOTE, "Tie '+' must be preceded by a note" },
    { ERR_040_HIERARCHY_INVALID, "Invalid hierachy of element '%s'" },
    { ERR_041_NESTING_INVALID, "Invalid nesting of opening and closing tags '%s'" },
    { ERR_042_CLEF_INCOMPLETE, "Incomplete clef cannot be parsed (Setting to G-2 if running in non-pedantic mode)" },
    { ERR_043_CLEF_INVALID_2ND, "Unexpected second character in clef sign; must be either '+' or '-'" },
    { ERR_044_CLEF_MENS, "Mixing mensural and non-mensural clefs" },
    { ERR_045_CLEF_INVALID_3RD, "Unexpected third character in clef sign; must be a digit" },
    { ERR_046_CLEF_INVALID, "Undefined clef: '%s'" },
    { ERR_047_TIMESIG_INCOMPLETE, "Incomplete time signature cannot be parsed (Setting to 4/4 if running in non-pedantic mode)" },
    { ERR_048_TIMESIG_INVALID, "Unsupported time signature: '%s'" },
    { ERR_049_TIMESIG_MENS, "Mensuration content cannot be parsed (Setting to 'O' if running in non-pedantic mode)" },
    { ERR_051_BARLINE, "Unsupported barline: '%s'" },
    { ERR_052_DURATION, "Duration content cannot be parsed (Setting to quarter note if running in non-pedantic mode)" },
    { ERR_053_DURATION_MENS3, "Duration '3' unsupported with mensural notation" },
    { ERR_054_DURATION_MENS5, "Duration '5' unsupported with mensural notation" },
    { ERR_055_KEYSIG_CHANGE, "Key signature change cannot occur more than once in a measure" },
    { ERR_056_TIMESIG_CHANGE, "Time signature change cannot occur more than once in a measure" },
    { ERR_057_MENSUR_CHANGE, "Mensur change cannot occur more than once in a measure" },
    { ERR_058_FERMATA_MREST, "Fermata on measure rest with extraneous content '%s'" }
```

Obviously, in Muscat, the messages can be adjusted as desired. For example, we do not need to have the extra information about the pedantic mode behaviour. So the list above will serve as a starting point in Muscat.

@xhero the JSON now contains a 'code' in addition to the 'text'. Most of the error messages do not have interpolation. For the ones that do, a `value` key is given. You can rely on the presence of `value` to determine if you need to do the interpolation of not.

For example:
```
@clef:CC1
@timesig:c/2
@key:C
@data:=1/4-''DxbC'tB/''tCC
```

```json
{
	"clef": {
		"code": 43,
		"column": 0,
		"row": 0,
		"text": "Unexpected second character in clef sign; must be either '+' or '-'",
		"type": "warning" 
	},
	"data": [
		{
			"code": 17,
			"column": 12,
			"row": 0,
			"text": "Invalid 't' not after a note",
			"type": "warning" 
		},
		{
			"code": 17,
			"column": 17,
			"row": 0,
			"text": "Invalid 't' not after a note",
			"type": "warning" 
		} 
	],
	"timesig": {
		"code": 48,
		"column": 0,
		"row": 0,
		"text": "Unsupported time signature: 'c\/2'",
		"type": "warning",
		"value": "c\/2" 
	} 
}
```

**Comment by lpugin** [comment]
One more added
```
    { ERR_050_INVALID_CHAR, "Invalid character(s) '%s'" },
```

**Comment by jenniferward** [comment]
We are revising the error messages internally and will make some suggestions to ensure that the warnings are as clear and user-friendly as possible. This is our working doc:
https://docs.google.com/spreadsheets/d/1bbQ2CzuyrgDTM3YTpm3FG4d_orTN5dqgjKJCiBXfzX8/edit?usp=sharing

**Comment by xhero** [comment]
Would you mind pushing them directly when you are done? when you encounter `%{value}` that is an interpolation with a value from the error message, like:
"invalid clef %{value}" becomes "invalid clef $F3"

**Comment by BaMikusi** [comment]
We shall surely not push anything directly without discussing the details with you -- for in some cases we are unsure what the exact error looks like, and so our "translation" will not necessarily be precise/appropriate. I shall now enter my suggestions and comments into the working doc and let you know once I am done -- then both Jennifer and you should take a look if we are on the right track.

**Comment by jenniferward** [comment]
Everyone should be able to edit now!

**Comment by BaMikusi** [comment]
I have now entered my first shots into the chart. Please take a look whether I correctly understood the nature of the errors (this is more for the Bern side) and whether I rephrased the notification texts appropriately (this is more for Jennifer). I am hoping that some of the issues I marked as "Not sure what the actual error is" might actually turn out to fall into the "irrelevant for Muscat cataloguing" category, and then we should not be very far away from a complete list of alternatives.

**Comment by jenniferward** [comment]
I made some silent edits to Balázs's rephrasings; you can check the version history to compare.

My bigger edits I marked in blue. Here, I departed strongly from the original and Balázs's revisions to get to the point quicker: it seems that oftentimes the error message describes what the situation is, but I think it would be more efficient to propose a solution to the user (i.e., that a '!' is missing rather than a group is open). 

Please double-check these because I'm not sure if my revisions cover all possibilities envisioned by the error message.

I have some notes in pink: these refer to things I checked in Muscat concerning the validation (maybe for Rodolfo) or the P&E code/guidelines (maybe for Andrew as he revises P&E).

I also included sample P&E for most of the errors, to help me visualize it and for quick reference.

Another thing, mostly for Andrew: Would it be worth checking the usage of the terms "bar" and "measure" in both the error messages and the P&E guidelines? I've been told that is an American/British difference, but the terms are so synonymous to me that I don't think I make a distinction at all--but maybe others do.

**Comment by BaMikusi** [comment]
Many thanks to Jennifer for the revisions -- I strove to render the technical messages in a more human-readable form, but giving more specific advice what to do (as she does) is of course even more helpful. That said, I have a few reservations, these I have now indicated in the comment field.

**Comment by jenniferward** [comment]
We're done with the table. Please check and import.

**Comment by lpugin** [comment]
FYI, I updated the Verovio messages accordingly. 
https://github.com/rism-digital/verovio/commit/17cf58fc7fa9a077e38923583b54172c07980221

These are **not** the ones that will be shown in Muscat. But they can appear elsewhere when using Verovio outside Muscat - e.g., in the https://www.verovio.org/pae-editor.html, so I tried to make them as similar as possible.

Quite a few will actually now be identical, but some remain not exactly the same because the serve a different purpose in Muscat. Here it is only about 'logging' validation errors. For example, instead of having in Muscat `Close the beam with '}' before the end of the measure.`, we will see `The beam must be closed with '}' before the end of the measure.` in Verovio.

**Comment by BaMikusi** [comment]
Thanks for the update. Obviously, the same messages would not be equally appropriate in different contexts, but it's certainly helpful if the two sets of notifications are not altogether different (and we are of course pleased if our suggestions could also prove useful for other Verovio audiences).

**Comment by xhero** [comment]
I would close this for now, and have specific tickets for eventual issues.
