### ISSUE TITLE
Add 787 as linkage between related sources

### ISSUE THREAD

**Issue by HirschSt** [rism-digital/muscat#999]
same as https://github.com/rism-international/tasks/issues/799

**Comment by xhero** [comment]
I would need a bit more info here, what should we do on the Muscat side of things?

**Comment by HirschSt** [comment]
Since we have 787 in the MarcConfiguration (except probably one indicator subfield $i), we had it in the past somewhere and there is maybe a related migration (I will check this) probably not too much to do at the moment.

**Comment by HirschSt** [comment]
Subfelder:

$i Information zur Beziehung [Dropdown-Liste]
$w RISM ID [Autocomplete/verlinken]
$n: Bemerkung / Note

Feldbezeichnungen:
Related RISM entry / Bezug zu RISM-Eintrag
Type of relationship / Art der Beziehung
RISM ID no. / RISM ID no.

Außerdem wird das Feld in den Block "References and notes" verschoben, zwischen 691 (Bibliopraphic reference) und 510 (RISM Series)
Weiteres Subfeld:

Validierung: Alle Subfelder müssen ausgefüllt werden.

Liste für Art der Beziehung:

Parallelquelle/Konkordanzen
Abschrift von einem Druck
Veröffentlicht in einem Druck
Weiteres Material
Weitere Version
Kontrafakta
Choralbearbeitung
Einlage

**Comment by jenniferward** [comment]
I propose that the order should be:
$w RISM ID no.
$i Type of relationship
$n Note 

EN for 787$i with abbreviated guidelines on use: 

- Concordant source: The related source is a concordant source that is directly relevant to the source in hand [i.e. not all possible concordances]
- Copied from: The source in hand was copied from the related source; the related source will usually be a print. [Some overlap with 596]
- Published in: The source in hand was published in the related source. [link will be to an edition]
- Additional material: The related source represents material that supplements the source in hand. Examples include: additional parts, instrumental parts, organ part, full score, vocal score, etc.
- Different version: The related source represents a version of the same piece that is different than the source in hand. Examples include: double chorus version, English version, full version, longer version, SATB version, version for soprano duet, etc.
- Contrafacta of: The source in hand is a contrafacta of the related source. [i.e. the physical related source was used for the contrafacta. This will be relatively rare.]
- Chorale arrangement of: The source in hand is a chorale arrangement of the related source; the related source will usually be a printed hymn book.
- Insert in: The source in hand is a piece that was inserted into a larger work, such as a suitcase aria inserted into an opera. 

Questions: 
1. Most relationships go cleanly in two directions, i.e. source A is an insert in source B, and source B has A as an insert. The nature of the inverse relationships is clear. However, with "additional material" and "different version", the exact nature can vary. For example, source A is a score, and the parts are in B. For A, I select "additional material" and write as a note "Parts." However, in the record for B, do I have to fill out the field again but say that A is a score? How will a user, viewing the record for B, know that A is the score?

2. The field 787 is currently used in 374 records (at least in the published OPAC data).
$g, $n, $s, $w
CH: ca. 50x, used for inserts
D: ca. 25x, used for inserts
US: ca. 300x, imported data, all one institution, used $w always and $g frequently (and 1x $n, never $s) in the MARC sense for indicating related records.

I know that the US group prefers to wait for 787 to be expanded before they adjust their data. Their records refer to a variety of the relationships named in $i above. Can we retain the subfields so that the working groups have time to adjust the data, then remove the subfields later? (This would mean that $w contains incorrect data, from the US at least, because they refer to other sources in OCLC, not Muscat).

**Comment by xhero** [comment]
A small recap of the discussion today, which involves point 1) in the previous comment. A solution could to move the relationship type and if the relationship is hierarchical or not (i.e. a copy of a score vs the libretto of a score). This offers the advantage that both elements in the relationship can easily get the type. We could also relatively easily automatically create the marc tag in both sources, either at edit or export stage.

**Comment by xhero** [comment]
Regarding the legacy data: since it is all non critical and some of it cannot be migrated by hand (i.e. OCoLC ids), a solution is to convert the tags to 599 so editors can fix them by hand (and delete the 599)

**Comment by HirschSt** [comment]
related https://github.com/rism-international/tasks/issues/904

done with maintenance

**Comment by jenniferward** [comment]
Here is a link to a table with the desired source relationships and available relationships in RDA, CIDOC-CDC, and LRMoo.
http://www.cidoc-crm.org/frbroo/sites/default/files/LRM-FRBRoo_V0.6%28PR%29%20-%20Rev.pdf

I think LRMoo comes the closest, but LRMoo clearly distinguishes between Work and Expression (for example) whereas our records do not.

https://docs.google.com/document/d/1ScEDcl5_m4KJE5zzi9HlhkmwLCttF173jhVOTX2YrRk/edit?usp=sharing

**Comment by ahankinson** [comment]
Looking at the docs, it seems that `$i` is used primarily for display purposes, while `$4` might be more suitable as a URI value for storing the relationship type. 

https://www.loc.gov/marc/bibliographic/bd76x78x.html

In the documentation they provide the example of the RDA Registry, which seems to be what we've been looking for all along in terms of a list of extensive relator codes with URIs. We probably want the "Unconstrained" properties, since this does not restrict us with specific FRBR relationship hierarchies (Work to Work, Work to Item, blah blah blah).

http://www.rdaregistry.info/Elements/u/

From @jenniferward 's list above:

Concordance: 
 - http://rdaregistry.info/Elements/u/P60208 (has concordance work)
 - http://rdaregistry.info/Elements/u/P60291 (is concordance to work)

Additional material:
 - http://rdaregistry.info/Elements/u/P60259
 - http://rdaregistry.info/Elements/u/P60281

Different version:
Lots to choose from (type 'version' in the search box on the page to narrow it down), but one that stands out:
 - http://rdaregistry.info/Elements/u/P60294 (is expanded version of work)

Copied:
 - http://rdaregistry.info/Elements/u/P60311 (is imitated from)

Insert:
 - http://rdaregistry.info/Elements/u/P60194 (is inserted in)

The others in the list might need a bit more clarification, but I'm sure there will be some available option?

So perhaps a revised proposal:

`$4` would have the RDA URI. This would be the value of the relationship stored in the M2M database field
`$i` would have the human-readable relationship ("has concordance work", etc.) This would only be stored in the MARC record.

**Comment by xhero** [comment]
Tags with no relator code (in Source):

- 100 (Person)
- 240 (StandardTitle)
- 650 (StandardTerm)
- 651 (Place)
- 657 (LiturgicalFeast)
- 691 (Publication)
- 730 (StandardTitle)
- 775 (Source)
- 852 (Institution)
- 930 (Work)

Tags with a relator code
- 700 (Person)
- 710 (Institution)

**Comment by jenniferward** [comment]
@ahankinson Thank you - That goes in a better direction, so I revised the table to prioritize this (the old table is under the new one):

https://docs.google.com/document/d/1ScEDcl5_m4KJE5zzi9HlhkmwLCttF173jhVOTX2YrRk/edit 

I highlighted an overlap, which might mean some of our terms should be combined.

My open question: I am fine with referring to the RDA relationship in the MARC record, but it would be more user-friendly to have different terms in the interface for some of the cases. 

@xhero I don't follow what these other fields have to do with the 787 field, but I probably missed something.

**Comment by lpugin** [comment]
Summary of  the current status in the doc. We now have a reduced number of possible relations. Here is a summary:
* _Correlated source:_ symmetrical - generic link for concordances and different versions
* _Additional material:_ symmetrical - link for sources where their material is complementing each other
* _Copied from:_ asymmetrical
* _Published in:_ asymmetrical
* _Arrangement of:_ asymmetrical
* Insert in: asymmetrical

Two comments:
* All asymmetrical links will have only one way in which they can be inserted in terms of cataloguing workflow. However, the document provides a list of reverse relations to be translated for display in the target source - if we decide to display them.
* _Published in_ is considered as asymmetrical in Muscat but will be using a symmetrical relationship - which should not be a problem

**Comment by ahankinson** [comment]
To clarify the document, I think $i is omitted, and the $4 is the URI with the namespace, e.g., `rdau:P60191`. This is according to the minutes of the 12 May 2021.

**Comment by xhero** [comment]
Yes, I already prepared Muscat to use $4. What are the codes to use for the relations in @lpugin's comment?

**Comment by BaMikusi** [comment]
Tiny question to Laurent's list: "Arrangement of" is by definition asymmetrical, but what if we cannot establish the actual direction in the arranging process? My guess: simply use "correlated source" instead, right? And "correlated source" would also be the plausible option for the editions with etiquettes, which we discussed at some length?

**Comment by ahankinson** [comment]
They're in the linked Google Doc in Jennifer's comment, which is what I was commenting on -- the third column says "$i" which we decided we would omit, and the fourth column says "$4" which gives the full URI, but we decided we would instead use the namespaced URI.

**Comment by xhero** [comment]
Ahhh ok! I did not see that the doc was updated! super!

**Comment by lpugin** [comment]
> Tiny question to Laurent's list: "Arrangement of" is by definition asymmetrical, but what if we cannot establish the actual direction in the arranging process? My guess: simply use "correlated source" instead, right? And "correlated source" would also be the plausible option for the editions with etiquettes, which we discussed at some length?

Yes, I think "correlated source" would be appropriate for cases for which the arrangement direction cannot be established.

**Comment by lpugin** [comment]
> Yes, I already prepared Muscat to use $4. What are the codes to use for the relations in @lpugin's comment?

E.g., `rdau:P60191`

**Comment by ahankinson** [comment]
You could also clarify the relationship (for humans, at least) in a `$n` field.

**Comment by jenniferward** [comment]
> > Tiny question to Laurent's list: "Arrangement of" is by definition asymmetrical, but what if we cannot establish the actual direction in the arranging process? My guess: simply use "correlated source" instead, right? And "correlated source" would also be the plausible option for the editions with etiquettes, which we discussed at some length?
> 
> Yes, I think "correlated source" would be appropriate for cases for which the arrangement direction cannot be established.

"arrangement of" will be used when we know the direction. It is a compromise/combination of "contrafacta of" and "chorale arrangement of" , which will be used by the catalogers who want to point out a known connection.

And in case I didn't mention this before: all of the subfields need to be required if the field is used.
